### ISSUE TITLE
Resolution change on input image

### ISSUE THREAD

**Issue by PavelPenyugalov** [subeeshvasu/2018_subeesh_epsr_eccvw#1]
Hello. Thanks for your project's code! 
I configured your project on my machine.
I tried with some images from Urban100 database and all is working very well!

And now I have a little question:
For example, if I need to scale input image with resolution 640x480 to 1920x1080(or something like this size) is it necessary to train model or I can set some parameters in demo.sh for command line? And if I can which parameter I need to put in to demo.sh?

Because images size in  Urban100 less than 256, and if I use images with >256 resolution size, the code is crashing.

Many Thanks!

**Comment by subeeshvasu** [comment]
Hi, the issue that you have pointed out is happening probably because of the memory requirement needed for a high-resolution input. As a solution, you can try splitting the input images into patches of smaller resolution (say of size < 256), then pass individual patches via the network and finally stitch the HR patches (from the network) to obtain the desired image. It's better to split the images into overlapping patches and then while stitching the images back ignore the overlapping regions at the boundaries. Let me know if you have any further queries.

**Comment by subeeshvasu** [comment]
A good example for patch-wise forward pass followed by stitching can be found in DBPN repository (https://github.com/alterzero/DBPN-Pytorch/). Look at the chop_forward function in eval.py.

**Comment by PavelPenyugalov** [comment]
Thanks for your quick answer and hints!
This error depends on RAM memory? Maybe if I'll add memory bar to motherboard then my problem will be solved(and if it help how much memory size I need)?

**Comment by subeeshvasu** [comment]
It's mostly because of the amount of GPU memory that the code needs for doing the forward pass of large resolution images. You may try out adding memory in the way you suggested but it may not work out. The best solution will be to do a patch-wise forward pass. Let me know if you find a solution other than patch-wise forward pass. :)

**Comment by PavelPenyugalov** [comment]
No problem)
If I'll get some results, I tell you about this.
